name: 🐍 Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: 🐍 Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Krishgoyal31
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=%237C3AED&color_dots=%230B1020,%23312E81,%236C28D9,%237C3AED,%2306B6D4&color_background=%23050816

      - name: 🚀 Publish snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
